name: GUT-tests

on:
  push:
    branches:
      - 'rick/unit_tests'

jobs:
  gut-godot42:
    name: Run GUT tests for Godot 4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Godot GUT CI Test
        uses: ceceppa/godot-gut-ci@main
        with:
          godot_version: 4.2
          gut_params: -gdir=res://tests/unit
          project_path: PuzzlePlatformer